### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by kanekikun420** [AndreySeVeN/ReplayRidor#1]
Hello. I wanted to compile your replaybot and I'm missing the LzmaLib.lib which contains LzmaLib.h could you send a download link?

**Comment by infyhr** [comment]
Download it from here: http://www.7-zip.org/sdk.html
and compile it yourself.

**Comment by AndreySeVeN** [comment]
> Download it from here: http://www.7-zip.org/sdk.html
