### ISSUE TITLE
Home button is working but program doesn't sense it

### ISSUE THREAD

**Issue by CyborgTed** [AndreySeVeN/ReplayRidor#2]
I launch the program, and I get the window asking to load the replay (Home). I press the Home button on my keyboard and nothing happens.

**Comment by CyborgTed** [comment]
If this has happened for someone else or even the creator, someone please tell me how to solve it

**Comment by AndreySeVeN** [comment]
Home button (it this moment) only work in osu!latest version.

**Comment by CyborgTed** [comment]
Currently I am on the latest version, Home button still fails to do anything.
Steps I am taking:
1: Run Osu
2: Run ReplayBot
3: Press Home
4: Nothing happens

**Comment by CyborgTed** [comment]
Been trying for the last hour, still nothing :/

**Comment by AndreySeVeN** [comment]
1) Run osu (latest version)
2) Open solo play
3) Run ReplayRidor
4) PressHome

**Comment by CyborgTed** [comment]
That worked! Sorry for the troubles, greatly appreciate this!
